#include "../include/ft_strace.h"

const t_syscall	g_syscall_table[2] =
{
{"read", 0, U_INT, CHAR_PTR, SIZE_T, NONE, NONE, NONE},
{"write", 1, U_INT, CONST_CHAR_PTR, SIZE_T, NONE, NONE, NONE},
{"open", 2, CONST_CHAR_PTR, INT, INT, NONE, NONE, NONE},
{"close", 3, U_INT, NONE, NONE, NONE, NONE, NONE},
{"stat", 4, CONST_CHAR_PTR, STRUCT_STAT_PTR, NONE, NONE, NONE, NONE},
{"fstat", 5, U_INT, STRUCT_STAT_PTR, NONE, NONE, NONE, NONE},
{"lstat", 6, fconst char *, STRUCT_STAT_PTR, NONE, NONE, NONE, NONE},
{"poll", 7, struct poll_fd *, U_INT, long, NONE, NONE, NONE},
{"lseek", 8, U_INT, off_t, U_INT, NONE, NONE, NONE},
{"mmap", 9, unsigned long, unsigned long, unsigned long, unsigned long, unsigned long, unsigned long},
{"mprotect", 10, unsigned long, SIZE_T, unsigned long, NONE, NONE, NONE},
{"munmap", 11, unsigned long, SIZE_T, NONE, NONE, NONE, NONE},
{"brk", 12, unsigned long, NONE, NONE, NONE, NONE, NONE},
{"rt_sigaction", 13, INT, const struct sigaction *, struct sigaction *, SIZE_T, NONE, NONE},
{"rt_sigprocmask", 14, INT, sigset_t *, sigset_t *, SIZE_T, NONE, NONE},
{"rt_sigreturn", 15, unsigned long, NONE, NONE, NONE, NONE, NONE},
{"ioctl", 16, U_INT, U_INT, unsigned long, NONE, NONE, NONE},
{"pread64", 17, unsigned long, CHAR_PTR, SIZE_T, loff_t, NONE, NONE},
{"pwrite64", 18, U_INT, CONST_CHAR_PTR, SIZE_T, loff_t, NONE, NONE},
{"readv", 19, unsigned long, const struct iovec *, unsigned long, NONE, NONE, NONE},
{"writev", 20, unsigned long, const struct iovec *, unsigned long, NONE, NONE, NONE},
{"access", 21, CONST_CHAR_PTR, INT, NONE, NONE, NONE, NONE},
{"pipe", 22, INT *, NONE, NONE, NONE, NONE, NONE},
{"select", 23, INT, fd_set *, fd_set *, fd_set*, struct timeval *, NONE},
{"sched_yield", 24, NONE, NONE, NONE, NONE, NONE, NONE},
{"mremap", 25, unsigned long, unsigned long, unsigned long, unsigned long, unsigned long, NONE},
{"msync", 26, unsigned long, SIZE_T, INT, NONE, NONE, NONE},
{"mincore", 27, unsigned long, SIZE_T, unsigned char *, NONE, NONE, NONE},
{"madvise", 28, unsigned long, SIZE_T, INT, NONE, NONE, NONE},
{"shmget", 29, key_t, SIZE_T, INT, NONE, NONE, NONE},
{"shmat", 30, INT, CHAR_PTR, INT, NONE, NONE, NONE},
{"shmctl", 31, INT, INT, struct shmid_ds *, NONE, NONE, NONE},
{"dup", 32, U_INT, NONE, NONE, NONE, NONE, NONE},
{"dup2", 33, U_INT, U_INT, NONE, NONE, NONE, NONE},
{"pause", 34, NONE, NONE, NONE, NONE, NONE, NONE},
{"nanosleep", 35, struct timespec *, struct timespec *, NONE, NONE, NONE, NONE},
{"getitimer", 36, INT, struct itimerval *, NONE, NONE, NONE, NONE},
{"alarm", 37, U_INT, NONE, NONE, NONE, NONE, NONE},
{"setitimer", 38, INT, struct itimerval *, struct itimerval *, NONE, NONE, NONE},
{"getpid", 39, NONE, NONE, NONE, NONE, NONE, NONE},
{"sendfile", 40, INT, INT, off_t *, SIZE_T, NONE, NONE},
{"socket", 41, INT, INT, INT, NONE, NONE, NONE},
{"connect", 42, INT, struct sockaddr *, INT, NONE, NONE, NONE},
{"accept", 43, INT, struct sockaddr *, INT *, NONE, NONE, NONE},
{"sendto", 44, INT, void *, SIZE_T, unsigned, struct sockaddr *, INT},
{"recvfrom", 45, INT, void *, SIZE_T, unsigned, struct sockaddr *, INT *},
{"sendmsg", 46, INT, struct msghdr *, unsigned, NONE, NONE, NONE},
{"recvmsg", 47, INT, struct msghdr *, U_INT, NONE, NONE, NONE},
{"shutdown", 48, INT, INT, NONE, NONE, NONE, NONE},
{"bind", 49, INT, struct sokaddr *, INT, NONE, NONE, NONE},
{"listen", 50, INT, INT, NONE, NONE, NONE, NONE},
{"getsockname", 51, INT, struct sockaddr *, INT *, NONE, NONE, NONE},
{"getpeername", 52, INT, struct sockaddr *, INT *, NONE, NONE, NONE},
{"socketpair", 53, INT, INT, INT, INT *, NONE, NONE},
{"setsockopt", 54, INT, INT, INT, CHAR_PTR, INT, NONE},
{"getsockopt", 55, INT, INT, INT, CHAR_PTR, INT *, NONE},
{"clone", 56, unsigned long, unsigned long, void *, void *, NONE, NONE},
{"fork", 57, NONE, NONE, NONE, NONE, NONE, NONE},
{"vfork", 58, NONE, NONE, NONE, NONE, NONE, NONE},
{"execve", 59, CONST_CHAR_PTR, CONST_CHAR_PTR, CONST_CHAR_PTR, NONE, NONE, NONE},
{"exit", 60, INT, NONE, NONE, NONE, NONE, NONE},
{"wait4", 61, pid_t, INT *, INT, struct rusage *, NONE, NONE},
{"kill", 62, pid_t, INT, NONE, NONE, NONE, NONE},
{"uname", 63, struct old_utsname *, NONE, NONE, NONE, NONE, NONE},
{"semget", 64, key_t, INT, INT, NONE, NONE, NONE},
{"semop", 65, INT, struct sembuf *, unsigned, NONE, NONE, NONE},
{"semctl", 66, INT, INT, INT, union semun, NONE, NONE},
{"shmdt", 67, CHAR_PTR, NONE, NONE, NONE, NONE, NONE},
{"msgget", 68, key_t, INT, NONE, NONE, NONE, NONE},
{"msgsnd", 69, INT, struct msgbuf *, SIZE_T, INT, NONE, NONE},
{"msgrcv", 70, INT, struct msgbuf *, SIZE_T, long, INT, NONE},
{"msgctl", 71, INT, INT, struct msqid_ds *, NONE, NONE, NONE},
{"fcntl", 72, U_INT, U_INT, unsigned long, NONE, NONE, NONE},
{"flock", 73, U_INT, U_INT, NONE, NONE, NONE, NONE},
{"fsync", 74, U_INT, NONE, NONE, NONE, NONE, NONE},
{"fdatasync", 75, U_INT, NONE, NONE, NONE, NONE, NONE},
{"truncate", 76, CONST_CHAR_PTR, long, NONE, NONE, NONE, NONE},
{"ftruncate", 77, U_INT, unsigned long, NONE, NONE, NONE, NONE},
{"getdents", 78, U_INT, struct linux_dirent *, U_INT, NONE, NONE, NONE},
{"getcwd", 79, CHAR_PTR, unsigned long, NONE, NONE, NONE, NONE},
{"chdir", 80, CONST_CHAR_PTR, NONE, NONE, NONE, NONE, NONE},
{"fchdir", 81, U_INT, NONE, NONE, NONE, NONE, NONE},
{"rename", 82, CONST_CHAR_PTR, CONST_CHAR_PTR, NONE, NONE, NONE, NONE},
{"mkdir", 83, CONST_CHAR_PTR, INT, NONE, NONE, NONE, NONE},
{"rmdir", 84, CONST_CHAR_PTR, NONE, NONE, NONE, NONE, NONE},
{"creat", 85, CONST_CHAR_PTR, INT, NONE, NONE, NONE, NONE},
{"link", 86, CONST_CHAR_PTR, CONST_CHAR_PTR, NONE, NONE, NONE, NONE},
{"unlink", 87, CONST_CHAR_PTR, NONE, NONE, NONE, NONE, NONE},
{"symlink", 88, CONST_CHAR_PTR, CONST_CHAR_PTR, NONE, NONE, NONE, NONE},
{"readlink", 89, CONST_CHAR_PTR, CHAR_PTR, INT, NONE, NONE, NONE},
{"chmod", 90, CONST_CHAR_PTR, mode_t, NONE, NONE, NONE, NONE},
{"fchmod", 91, U_INT, mode_t, NONE, NONE, NONE, NONE},
{"chown", 92, CONST_CHAR_PTR, uid_t, gid_t, NONE, NONE, NONE},
{"fchown", 93, U_INT, uid_t, gid_t, NONE, NONE, NONE},
{"lchown", 94, CONST_CHAR_PTR, uid_t, gid_t, NONE, NONE, NONE},
{"umask", 95, INT, NONE, NONE, NONE, NONE, NONE},
{"gettimeofday", 96, struct timeval *, struct timezone *, NONE, NONE, NONE, NONE},
{"getrlimit", 97, U_INT, struct rlimit *, NONE, NONE, NONE, NONE},
{"getrusage", 98, INT, struct rusage *, NONE, NONE, NONE, NONE},
{"sysinfo", 99, struct sysinfo *, NONE, NONE, NONE, NONE, NONE},
{"times", 100, struct sysinfo *, NONE, NONE, NONE, NONE, NONE},
{"ptrace", 101, long, long, unsigned long, unsigned long, NONE, NONE},
{"getuid", 102, NONE, NONE, NONE, NONE, NONE, NONE},
{"syslog", 103, INT, CHAR_PTR, INT, NONE, NONE, NONE},
{"getgid", 104, NONE, NONE, NONE, NONE, NONE, NONE},
{"setuid", 105, uid_t, NONE, NONE, NONE, NONE, NONE},
{"setgid", 106, gid_t, NONE, NONE, NONE, NONE, NONE},
{"geteuid", 107, NONE, NONE, NONE, NONE, NONE, NONE},
{"getegid", 108, NONE, NONE, NONE, NONE, NONE, NONE},
{"setpgid", 109, pid_t, pid_t, NONE, NONE, NONE, NONE},
{"getppid", 110, NONE, NONE, NONE, NONE, NONE, NONE},
{"getpgrp", 111, NONE, NONE, NONE, NONE, NONE, NONE},
{"setsid", 112, NONE, NONE, NONE, NONE, NONE, NONE},
{"setreuid", 113, uid_t, uid_t, NONE, NONE, NONE, NONE},
{"setregid", 114, gid_t, gid_t, NONE, NONE, NONE, NONE},
{"getgroups", 115, INT, gid_t *, NONE, NONE, NONE, NONE},
{"setgroups", 116, INT, gid_t *, NONE, NONE, NONE, NONE},
{"setresuid", 117, uid_t *, uid_t *, uid_t *, NONE, NONE, NONE},
{"getresuid", 118, uid_t *, uid_t *, uid_t *, NONE, NONE, NONE},
{"setresgid", 119, gid_t, gid_t, gid_t, NONE, NONE, NONE},
{"getresgid", 120, gid_t *, gid_t *, gid_t *, NONE, NONE, NONE},
{"getpgid", 121, pid_t, NONE, NONE, NONE, NONE, NONE},
{"setfsuid", 122, uid_t, NONE, NONE, NONE, NONE, NONE},
{"setfsgid", 123, gid_t, NONE, NONE, NONE, NONE, NONE},
{"getsid", 124, pid_t, NONE, NONE, NONE, NONE, NONE},
{"capget", 125, cap_user_header_t, cap_user_data_t, NONE, NONE, NONE, NONE},
{"capset", 126, cap_user_header_t, const cap_user_data_t, NONE, NONE, NONE, NONE},
{"rt_sigpending", 127, sigset_t *, SIZE_T, NONE, NONE, NONE, NONE},
{"rt_sigtimedwait", 128, const sigset_t *, siginfo_t *, const struct timespec *, SIZE_T, NONE, NONE},
{"rt_sigqueueinfo", 129, pid_t, INT, siginfo_t *, NONE, NONE, NONE},
{"rt_sigsuspend", 130, sigset_t *, SIZE_T, NONE, NONE, NONE, NONE},
{"sigaltstack", 131, const stack_t *, stack_t *, NONE, NONE, NONE, NONE},
{"utime", 132, CHAR_PTR, struct utimbuf *, NONE, NONE, NONE, NONE},
{"mknod", 133, CONST_CHAR_PTR, umode_t, unsigned, NONE, NONE, NONE},
{"uselib", 134, NONE, NONE, NONE, NONE, NONE, NONE},
{"personality", 135, U_INT, NONE, NONE, NONE, NONE, NONE},
{"ustat", 136, unsigned, struct ustat *, NONE, NONE, NONE, NONE},
{"statfs", 137, CONST_CHAR_PTR, struct statfs *, NONE, NONE, NONE, NONE},
{"fstatfs", 138, U_INT, struct statfs *, NONE, NONE, NONE, NONE},
{"sysfs", 139, INT, unsigned long, unsigned long, NONE, NONE, NONE},
{"getpriority", 140, INT, INT, NONE, NONE, NONE, NONE},
{"setpriority", 141, INT, INT, INT, NONE, NONE, NONE},
{"sched_setparam", 142, pid_t, struct sched_param *, NONE, NONE, NONE, NONE},
{"sched_getparam", 143, pid_t, struct sched_param *, NONE, NONE, NONE, NONE},
{"sched_setscheduler", 144, pid_t, INT, struct sched_param *, NONE, NONE, NONE},
{"sched_getscheduler", 145, pid_t, NONE, NONE, NONE, NONE, NONE},
{"sched_get_priority_max", 146, INT, NONE, NONE, NONE, NONE, NONE},
{"sched_get_priority_min", 147, INT, NONE, NONE, NONE, NONE, NONE},
{"sched_rr_get_interval", 148, pid_t, struct timespec *, NONE, NONE, NONE, NONE},
{"mlock", 149, unsigned long, SIZE_T, NONE, NONE, NONE, NONE},
{"munlock", 150, unsigned long, SIZE_T, NONE, NONE, NONE, NONE},
{"mlockall", 151, INT, NONE, NONE, NONE, NONE, NONE},
{"munlockall", 152, NONE, NONE, NONE, NONE, NONE, NONE},
{"vhangup", 153, NONE, NONE, NONE, NONE, NONE, NONE},
{"modify_ldt", 154, INT, void *, unsigned long, NONE, NONE, NONE},
{"pivot_root", 155, CONST_CHAR_PTR, CONST_CHAR_PTR, NONE, NONE, NONE, NONE},
{"_sysctl", 156, struct __sysctl_args *, NONE, NONE, NONE, NONE, NONE},
{"prctl", 157, INT, unsigned long, unsigned long, unsigned long, NONE, unsigned long},
{"arch_prctl", 158, struct task_struct *, INT, unsigned long *, NONE, NONE, NONE},
{"adjtimex", 159, struct timex *, NONE, NONE, NONE, NONE, NONE},
{"setrlimit", 160, U_INT, struct rlimit *, NONE, NONE, NONE, NONE},
{"chroot", 161, CONST_CHAR_PTR, NONE, NONE, NONE, NONE, NONE},
{"sync", 162, NONE, NONE, NONE, NONE, NONE, NONE},
{"acct", 163, CONST_CHAR_PTR, NONE, NONE, NONE, NONE, NONE},
{"settimeofday", 164, struct timeval *, struct timezone *, NONE, NONE, NONE, NONE},
{"mount", 165, CHAR_PTR, CHAR_PTR, CHAR_PTR, unsigned long, void *, NONE},
{"umount2", 166, CONST_CHAR_PTR, INT, NONE, NONE, NONE, NONE},
{"swapon", 167, CONST_CHAR_PTR, INT, NONE, NONE, NONE, NONE},
{"swapoff", 168, CONST_CHAR_PTR, NONE, NONE, NONE, NONE, NONE},
{"reboot", 169, INT, INT, U_INT, void *, NONE, NONE},
{"sethostname", 170, CHAR_PTR, INT, NONE, NONE, NONE, NONE},
{"setdomainname", 171, CHAR_PTR, INT, NONE, NONE, NONE, NONE},
{"iopl", 172, U_INT, struct pt_regs *, NONE, NONE, NONE, NONE},
{"ioperm", 173, unsigned long, unsigned long, INT, NONE, NONE, NONE},
{"create_module", 174, NONE, NONE, NONE, NONE, NONE, NONE},
{"init_module", 175, void *, unsigned long, CONST_CHAR_PTR, NONE, NONE, NONE},
{"delete_module", 176, const chat *, U_INT, NONE, NONE, NONE, NONE},
{"get_kernel_syms", 177, NONE, NONE, NONE, NONE, NONE, NONE},
{"query_module", 178, NONE, NONE, NONE, NONE, NONE, NONE},
{"quotactl", 179, U_INT, CONST_CHAR_PTR, qid_t, void *, NONE, NONE},
{"nfsservctl", 180, NONE, NONE, NONE, NONE, NONE, NONE},
{"getpmsg", 181, NONE, NONE, NONE, NONE, NONE, NONE},
{"putpmsg", 182, NONE, NONE, NONE, NONE, NONE, NONE},
{"afs_syscall", 183, NONE, NONE, NONE, NONE, NONE, NONE},
{"tuxcall", 184, NONE, NONE, NONE, NONE, NONE, NONE},
{"security", 185, NONE, NONE, NONE, NONE, NONE, NONE},
{"gettid", 186, NONE, NONE, NONE, NONE, NONE, NONE},
{"readahead", 187, INT, loff_t, SIZE_T, NONE, NONE, NONE},
{"setxattr", 188, CONST_CHAR_PTR, CONST_CHAR_PTR, const void *, SIZE_T, INT, NONE},
{"lsetxattr", 189, CONST_CHAR_PTR, CONST_CHAR_PTR, const void *, SIZE_T, INT, NONE},
{"fsetxattr", 190, INT, CONST_CHAR_PTR, const void *, SIZE_T, INT, NONE},
{"getxattr", 191, CONST_CHAR_PTR, CONST_CHAR_PTR, void *, SIZE_T, NONE, NONE},
{"lgetxattr", 192, CONST_CHAR_PTR, CONST_CHAR_PTR, void *, SIZE_T, NONE, NONE},
{"fgetxattr", 193, INT, const har *, void *, SIZE_T, NONE, NONE},
{"listxattr", 194, CONST_CHAR_PTR, CHAR_PTR, SIZE_T, NONE, NONE, NONE},
{"llistxattr", 195, CONST_CHAR_PTR, CHAR_PTR, SIZE_T, NONE, NONE, NONE},
{"flistxattr", 196, INT, CHAR_PTR, SIZE_T, NONE, NONE, NONE},
{"removexattr", 197, CONST_CHAR_PTR, CONST_CHAR_PTR, NONE, NONE, NONE, NONE},
{"lremovexattr", 198, CONST_CHAR_PTR, CONST_CHAR_PTR, NONE, NONE, NONE, NONE},
{"fremovexattr", 199, INT, CONST_CHAR_PTR, NONE, NONE, NONE, NONE},
{"tkill", 200, pid_t, ing, NONE, NONE, NONE, NONE},
{"time", 201, time_t *, NONE, NONE, NONE, NONE, NONE},
{"futex", 202, u32 *, INT, u32, struct timespec *, u32 *, u32},
{"sched_setaffinity", 203, pid_t, U_INT, unsigned long *, NONE, NONE, NONE},
{"sched_getaffinity", 204, pid_t, U_INT, unsigned long *, NONE, NONE, NONE},
{"set_thread_area", 205, NONE, NONE, NONE, NONE, NONE, NONE},
{"io_setup", 206, unsigned, aio_context_t *, NONE, NONE, NONE, NONE},
{"io_destroy", 207, aio_context_t, NONE, NONE, NONE, NONE, NONE},
{"io_getevents", 208, aio_context_t, long, long, struct io_event *, NONE, NONE},
{"io_submit", 209, aio_context_t, long, struct iocb *, NONE, NONE, NONE},
{"io_cancel", 210, aio_context_t, struct iocb *, struct io_event *, NONE, NONE, NONE},
{"get_thread_area", 211, NONE, NONE, NONE, NONE, NONE, NONE},
{"lookup_dcookie", 212, u64, long, long, NONE, NONE, NONE},
{"epoll_create", 213, INT, NONE, NONE, NONE, NONE, NONE},
{"epoll_ctl_old", 214, NONE, NONE, NONE, NONE, NONE, NONE},
{"epoll_wait_old", 215, NONE, NONE, NONE, NONE, NONE, NONE},
{"remap_file_pages", 216, unsigned long, unsigned long, unsigned long, unsigned long, unsigned long, NONE},
{"getdents64", 217, U_INT, struct linux_dirent64 *, U_INT, NONE, NONE, NONE},
{"set_tid_address", 218, INT *, NONE, NONE, NONE, NONE, NONE},
{"restart_syscall", 219, NONE, NONE, NONE, NONE, NONE, NONE},
{"semtimedop", 220, INT, struct sembuf *, unsigned, const struct timespec *, NONE, NONE},
{"fadvise64", 221, INT, loff_t, SIZE_T, INT, NONE, NONE},
{"timer_create", 222, const clockid_t, struct sigevent *, timer_t *, NONE, NONE, NONE},
{"timer_settime", 223, timer_t, INT, const struct itimerspec *, struct itimerspec *, NONE, NONE},
{"timer_gettime", 224, timer_t, struct itimerspec *, NONE, NONE, NONE, NONE},
{"timer_getoverrun", 225, timer_t, NONE, NONE, NONE, NONE, NONE},
{"timer_delete", 226, timer_t, NONE, NONE, NONE, NONE, NONE},
{"clock_settime", 227, const clockid_t, const struct timespec *, NONE, NONE, NONE, NONE},
{"clock_gettime", 228, const clockid_t, struct timespec *, NONE, NONE, NONE, NONE},
{"clock_getres", 229, const clockid_t, struct timespec *, NONE, NONE, NONE, NONE},
{"clock_nanosleep", 230, const clockid_t, INT, const struct timespec *, struct timespec *, NONE, NONE},
{"exit_group", 231, INT, NONE, NONE, NONE, NONE, NONE},
{"epoll_wait", 232, INT, struct epoll_event *, INT, INT, NONE, NONE},
{"epoll_ctl", 233, INT, INT, INT, struct epoll_event *, NONE, NONE},
{"tgkill", 234, pid_t, pid_t, INT, NONE, NONE, NONE},
{"utimes", 235, CHAR_PTR, struct timeval *, NONE, NONE, NONE, NONE},
{"vserver", 236, NONE, NONE, NONE, NONE, NONE, NONE},
{"mbind", 237, unsigned long, unsigned long, unsigned long, unsigned long *, unsigned long, unsigned},
{"set_mempolicy", 238, INT, unsigned long *, unsigned long, NONE, NONE, NONE},
{"get_mempolicy", 239, INT *, unsigned long *, unsigned long, unsigned long, unsigned long, NONE},
{"mq_open", 240, CONST_CHAR_PTR, INT, mode_t, struct mq_attr *, NONE, NONE},
{"mq_unlink", 241, CONST_CHAR_PTR, NONE, NONE, NONE, NONE, NONE},
{"mq_timedsend", 242, mqd_t, CONST_CHAR_PTR, SIZE_T, U_INT, const stuct timespec *, NONE},
{"mq_timedreceive", 243, mqd_t, CHAR_PTR, SIZE_T, U_INT *, const struct timespec *, NONE},
{"mq_notify", 244, mqd_t, const struct sigevent *, NONE, NONE, NONE, NONE},
{"mq_getsetattr", 245, mqd_t, const struct mq_attr *, struct mq_attr *, NONE, NONE, NONE},
{"kexec_load", 246, unsigned long, unsigned long, struct kexec_segment *, unsigned long, NONE, NONE},
{"waitid", 247, INT, pid_t, struct siginfo *, INT, struct rusage *, NONE},
{"add_key", 248, CONST_CHAR_PTR, CONST_CHAR_PTR, const void *, SIZE_T, NONE, NONE},
{"request_key", 249, CONST_CHAR_PTR, CONST_CHAR_PTR, CONST_CHAR_PTR, key_serial_t, NONE, NONE},
{"keyctl", 250, INT, unsigned long, unsigned long, unsigned long, unsigned long, NONE},
{"ioprio_set", 251, INT, INT, INT, NONE, NONE, NONE},
{"ioprio_get", 252, INT, INT, NONE, NONE, NONE, NONE},
{"inotify_init", 253, NONE, NONE, NONE, NONE, NONE, NONE},
{"inotify_add_watch", 254, INT, CONST_CHAR_PTR, u32, NONE, NONE, NONE},
{"inotify_rm_watch", 255, INT, __s32, NONE, NONE, NONE, NONE},
{"migrate_pages", 256, pid_t, unsigned long, const unsigned long *, const unsigned long *, NONE, NONE},
{"openat", 257, INT, CONST_CHAR_PTR, INT, INT, NONE, NONE},
{"mkdirat", 258, INT, CONST_CHAR_PTR, INT, NONE, NONE, NONE},
{"mknodat", 259, INT, CONST_CHAR_PTR, INT, unsigned, NONE, NONE},
{"fchownat", 260, INT, CONST_CHAR_PTR, uid_t, gid_t, INT, NONE},
{"futimesat", 261, INT, CONST_CHAR_PTR, struct timeval *, NONE, NONE, NONE},
{"newfstatat", 262, INT, CONST_CHAR_PTR, STRUCT_STAT_PTR, INT, NONE, NONE},
{"unlinkat", 263, INT, CONST_CHAR_PTR, INT, NONE, NONE, NONE},
{"renameat", 264, INT, CONST_CHAR_PTR, INT, CONST_CHAR_PTR, NONE, NONE},
{"linkat", 265, INT, CONST_CHAR_PTR, INT, CONST_CHAR_PTR, INT, NONE},
{"symlinkat", 266, CONST_CHAR_PTR, INT, CONST_CHAR_PTR, NONE, NONE, NONE},
{"readlinkat", 267, INT, CONST_CHAR_PTR, CHAR_PTR, INT, NONE, NONE},
{"fchmodat", 268, INT, CONST_CHAR_PTR, mode_t, NONE, NONE, NONE},
{"faccessat", 269, INT, CONST_CHAR_PTR, INT, NONE, NONE, NONE},
{"pselect6", 270, INT, fd_set *, fd_set *, fd_set *, struct timespec *, void *},
{"ppoll", 271, struct pollfd *, U_INT, struct timespec *, const sigset_t *, SIZE_T, NONE},
{"unshare", 272, unsigned long, NONE, NONE, NONE, NONE, NONE},
{"set_robust_list", 273, struct robust_list_head *, SIZE_T, NONE, NONE, NONE, NONE},
{"get_robust_list", 274, INT, struct robust_list_head *, SIZE_T *, NONE, NONE, NONE},
{"splice", 275, INT, loff_t *, INT, loff_t *, SIZE_T, U_INT},
{"tee", 276, INT, INT, SIZE_T, U_INT, NONE, NONE},
{"sync_file_range", 277, long, loff_t, loff_t, long, NONE, NONE},
{"vmsplice", 278, INT, const struct iovec *, unsigned long, U_INT, NONE, NONE},
{"move_pages", 279, pid_t, unsigned long, const void *, const int *, INT *, INT},
{"utimensat", 280, INT, CONST_CHAR_PTR, struct timespec *, INT, NONE, NONE},
{"epoll_pwait", 281, INT, struct epoll_event *, INT, INT, const sigset_t *, SIZE_T},
{"signalfd", 282, INT, sigset_t *, SIZE_T, NONE, NONE, NONE},
{"timerfd_create", 283, INT, INT, NONE, NONE, NONE, NONE},
{"eventfd", 284, U_INT, NONE, NONE, NONE, NONE, NONE},
{"fallocate", 285, long, long, loff_t, loff_t, NONE, NONE},
{"timerfd_settime", 286, INT, INT, const struct itimerspec *, struct itimerspec *, NONE, NONE},
{"timerfd_gettime", 287, INT, struct itimerspec *, NONE, NONE, NONE, NONE},
{"accept4", 288, INT, struct sockaddr *, INT *, INT, NONE, NONE},
{"signalfd4", 289, INT, sigset_t *, SIZE_T, INT, NONE, NONE},
{"eventfd2", 290, U_INT, INT, NONE, NONE, NONE, NONE},
{"epoll_create1", 291, INT, NONE, NONE, NONE, NONE, NONE},
{"dup3", 292, U_INT, U_INT, INT, NONE, NONE, NONE},
{"pipe2", 293, INT *, INT, NONE, NONE, NONE, NONE},
{"inotify_init1", 294, INT, NONE, NONE, NONE, NONE, NONE},
{"preadv", 295, unsigned long, const struct iovec *, unsigned long, unsigned long, unsigned long, NONE},
{"pwritev", 296, unsigned long, const struct iovec *, unsigned long, unsigned long, unsigned long, NONE},
{"rt_tgsigqueueinfo", 297, pid_t, pid_t, INT, siginfo_t *, NONE, NONE},
{"perf_event_open", 298, struct perf_event_attr *, pid_t, INT, INT, unsigned long, NONE},
{"recvmmsg", 299, INT, struct msghdr *, U_INT, U_INT, struct timespec *, NONE},
{"fanotify_init", 300, U_INT, U_INT, NONE, NONE, NONE, NONE},
{"fanotify_mark", 301, long, long, __u64, long, long, NONE},
{"prlimit64", 302, pid_t, U_INT, const struct rlimit64 *, struct rlimit64 *, NONE, NONE},
{"name_to_handle_at", 303, INT, CONST_CHAR_PTR, struct file_handle *, INT *, INT, NONE},
{"open_by_handle_at", 304, INT, CONST_CHAR_PTR, struct file_handle *, INT *, INT, NONE},
{"clock_adjtime", 305, clockid_t, struct timex *, NONE, NONE, NONE, NONE},
{"syncfs", 306, INT, NONE, NONE, NONE, NONE, NONE},
{"sendmmsg", 307, INT, struct mmsghdr *, U_INT, U_INT, NONE, NONE},
{"setns", 308, INT, INT, NONE, NONE, NONE, NONE},
{"getcpu", 309, unsigned *, unsigned *, struct getcpu_cache *, NONE, NONE, NONE},
{"process_vm_readv", 310, pid_t, const struct iovec *, unsigned long, const struct iovec *, unsigned long, unsigned long},
{"process_vm_writev", 311, pid_t, const struct iovec *, unsigned long, const struct iovcc *, unsigned long, unsigned long},
{"kcmp", 312, pid_t, pid_t, INT, unsigned long, unsigned long, NONE},
{"finit_module", 313, INT, const char __user *, INT, NONE, NONE, NONE},
{"sched_setattr", 314, pid_t, struct sched_attr __user *, U_INT, NONE, NONE, NONE},
{"sched_getattr", 315, pid_t, struct sched_attr __user *, U_INT, U_INT, NONE, NONE},
{"renameat2", 316, INT, const char __user *, INT, const char __user *, U_INT, NONE},
{"seccomp", 317, U_INT, U_INT, const char __user *, NONE, NONE, NONE},
{"getrandom", 318, char __user *, SIZE_T, U_INT, NONE, NONE, NONE},
{"memfd_create", 319, const char __user *, unsigned
int, NONE, NONE, NONE, NONE},
{"kexec_file_load", 320, INT, INT, unsigned long, const char __user *, unsigned long, NONE},
{"bpf", 321, INT, union bpf_attr *, U_INT, NONE, NONE, NONE},
{"stub_execveat", 322, INT, const char __user *, const char __user *, const char __user *, INT, NONE},
{"userfaultfd", 323, INT, NONE, NONE, NONE, NONE, NONE},
{"membarrier", 324, INT, INT, NONE, NONE, NONE, NONE},
{"mlock2", 325, unsigned long, SIZE_T, INT, NONE, NONE, NONE},
{"copy_file_range", 326, INT, loff_t __user *, INT, loff_t __user *, SIZE_T, U_INT},
{"preadv2", 327, unsigned long, const struct iovec __user *, unsigned long, unsigned long, unsigned long, INT},
{"pwritev2", 328, unsigned long, const struct iovec __user *, unsigned long, unsigned long, unsigned long, INT}

	{NULL, NONE, NONE, NONE, NONE, NONE, NONE, NONE, {NONE}}
};

void	usage(int argc)
{
	if (argc == 1) {
		fprintf(stderr,
		"ft_strace: must have PROG [ARGS]\nTry 'strace -h' for more information.\n");
		exit (EXIT_FAILURE);
	}
}

int	main(int argc, char **argv)
{
	pid_t					child = 0;
	char					*const args[] = {NULL};
	int						status = 0;
	struct user_regs_struct	regs;
	uint64_t				old = 0;
	char message[1000];
	char* temp_char2 = message;

	usage(argc);
	child = fork();
	if (child == -1) {
		perror("fork()");
	}
	else if (child == 0) {
		execvp(argv[1], args);
	} else {
		kill(child, SIGSTOP);
		ptrace(PTRACE_SEIZE, child, NULL, NULL);
		waitpid(child, &status, 0);
		while (1) {
			ptrace(PTRACE_SYSCALL, child, NULL, NULL);
			waitpid(child, &status, 0);
			ptrace(PTRACE_GETREGS, child, NULL, &regs);
			/*printf("orig_rax : 0x%llx\t | ", regs.orig_rax);*/
			/*if (regs.rdi != 0x0) {*/
				/*printf("rdi : %llx\t |", regs.rdi);*/
			/*} else {*/
				/*printf("NULL |");*/
			/*}*/

			/*if (regs.orig_rax == 0x0) {*/
				/*if ()*/
				/*[>sprintf(fdpath,"/proc/%u/fd/%llu", child, regs.rdi);<]*/
				/*[>size = readlink(fdpath, &filepath, 256);<]*/
				/*[>filepath[size] = '\0';<]*/
				/*[>printf("File-%s-\n", filepath);<]*/
			/*}*/
			if (regs.orig_rax == 0x0) {
				printf("Syscall = %s\t| ", g_syscall_table[regs.orig_rax].name);
				if (g_syscall_table[regs.orig_rax].rdi == U_INT) {
					printf("rdi = %lld\t| ", regs.rdi);
				}
				if (g_syscall_table[regs.orig_rax].rsi == CHAR_PTR) {
					printf("rsi = %llu", regs.rsi);
				}
			}
			old = regs.orig_rax;
			puts("");
			ptrace(PTRACE_SYSCALL, child, NULL, NULL);
			waitpid(child, &status, 0);
			if (WIFEXITED(status))
				break ;
		}
	}
	return (0);
}
